### ISSUE TITLE
AGR section should contain other mines

### ISSUE THREAD

**Issue by nuin** [intermine/redgenes#720]
Hi

I noticed that Bluegenes still has only WormMine in the AGR section. At least Yeastmine should be added, and I think maybe FlyMine too. The other MODs are not in the same release.

Thanks

**Comment by rachellyne** [comment]
FlyMine is currently maintained by us rather than FlyBase.  I am not sure, but maybe FlyBase are going to start a FlyMine at some point (or take-over) as part of AGR?

**Comment by nuin** [comment]
Yes, we discussed this before, but at least YeastMine should be in the AGR section. We have AllianceMine also running.

**Comment by danielabutano** [comment]
Hi @nuin, I have updated YeastMine
