### ISSUE TITLE
underlying mine release

### ISSUE THREAD

**Issue by sergiocontrino** [intermine/redgenes#721]
it would be nice to expose the release number in the bluegenes mine home page (property project.releaseVersion), probably between the title and the subtitle

**Comment by heralden** [comment]
This is present under *Build:* when you hover over **InterMine** in the footer. Is this sufficient or does it need to be more visible?

**Comment by sergiocontrino** [comment]
thank you @uosl , i think a position as suggested before would be better, unless you find it ruins the page..
