### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by nuin** [intermine/redgenes#752]
Trying to login to WormMine from a Bluegenes deployment (WormMine is not the main mine). Is this a normal feature? 

![image](https://user-images.githubusercontent.com/6273/135647671-353d8eea-df69-4348-b81d-7de8dacc5cf9.png)

**Comment by heralden** [comment]
No, it seems to have failed with an empty error.

I tried to reproduce by creating an account and logging into wormmine from http://bluegenes.apps.intermine.org/wormmine but it worked fine. Are you able to reproduce it in your deployment? Could you provide the response JSON from the login request in the devtools network tab?
