### ISSUE TITLE
Can we improve the publication summary display?

### ISSUE THREAD

**Issue by rachellyne** [intermine/redgenes#761]
The abstract text is usually quite long and seems to push other fields into being displayed in the wrong place.  This was brought up by Val for pombeMine but applies to all mines.

**Comment by heralden** [comment]
This is the same as https://github.com/intermine/bluegenes/issues/642 right?

I'll fix it for the coming release.

**Comment by rachellyne** [comment]
Yes, sorry I didn't look!

**Comment by heralden** [comment]
No worries! I'll close this then as it's the same issue
