### ISSUE TITLE
error rerunning existing query

### ISSUE THREAD

**Issue by ValWood** [intermine/redgenes#773]
I was trying to rerun a query to answer
https://github.com/pombase/pombase-chado/issues/929

but I got an error

TypeError: Cannot read properties of null (reading 'toLowerCase')

    in r.
    in ul
    in li
    in r.
    in ul
    in li
    in r.
    in ul
    in div
    in Dmb
    in div
    in Kmb
    in div
    in div
    in Lmb
    in div
    in div
    in div
    in div
    in Umb
    in utb
    in main
    in div
    in BlueGenesRootErrorBoundary
    in Q.
    in vtb

**Comment by heralden** [comment]
Are you able to reproduce the issue? What actions in the UI were you doing before the error?

**Comment by ValWood** [comment]
My saved queries are not there becasue I didn't log in. MAybe this was why the rerun of the query didn't work. I can't dig into it for the next few days as I am in meetings but I will see if I can repeat early next week.
v

**Comment by ValWood** [comment]
Select "GO annotation"
Select "Evidence"
Switch from Evidence to "GO evidence":
elect "with"
Select "DB identifier"

to get this error.

Note this 'workflow' for a query isn't quite right anyway 
@rachellyne  knows about the issues here  (some issue with conflation/modelling  of 'Evidence' and 'GO evidence') that is presumably reported in another ticket. Addressing that issue  might make this error irrelevant).

**Comment by heralden** [comment]
Thanks, I'm able to reproduce it on Humanmine. Looks like an issue with adding a descendant view to a type constraint (Evidence constrained to GO Evidence) not yet in the query's *view*.

**Comment by ValWood** [comment]
I think there is also an issue with the way the evidence is currently  is modelled anyways....

**Comment by heralden** [comment]
That may be, but I'm able to reproduce it also with other classes on Humanmine, e.g.: Select root data type Gene, select Child Features and type constrain to CRM, select TF Binding Sites and add Primary Identifier to view.
