### ISSUE TITLE
possible bug in list reporting

### ISSUE THREAD

**Issue by ValWood** [intermine/redgenes#790]
example
Run query from template
http://met1.gen.private.cam.ac.uk:5050/pombemine/templates
(change this to "all genes" by removing the gene name constraint)

Gives 2253 rows (this seems  correct).
I want to access the list of unique genes here.

The number of unique identifiers reported  in the "GeneDB identifier" column, is correctly 1,373.
However, when I attempt to download this list the download reports (and downloads) 3575 genes.

@rachellyne  this is the issue I encountered yesterrday.

**Comment by danielabutano** [comment]
@ValWood which is the template you talk about? there are so many templates involving genes :)

**Comment by ValWood** [comment]
This was gene to Mondo.
However this issue might be a consequence of how the PomBase disease assignments are  currently modelled (does not  make sense for PomBeMine. In PomBase MOndo ID  is attached to a pombe gene as a 'disease association'  (we do not load the human genes), but in Intermine we need to attach to a human gene (like OMIM), or link MONDO to OMIM  in some way using the mapping file.

so this query will  be presented removed. For  now I would not worry about this one, if I see the same issue with another query I will open another ticket.

@rachellyne  is there a ticket for  loading MonDO-> OMIM mapping or human->Mondo disease associations ?
(it would be really nice if this could. be integrated in some way via the mapping data)

**Comment by danielabutano** [comment]
@ValWood  I removed the lookup contraint from the gene-> mondo I have in return 4006 rows and there are 1406 genes....it's weird
In any case when I export the result in tsv format, I have 4006 rows which is correct.

**Comment by rachellyne** [comment]
@danielabutano   how many genes do you get when you save a list.  The Rows/genes sounds ok.

**Comment by ValWood** [comment]
Ignore my comment above. This was the gene-> OMIM query, not the MONDI and it is still a problem. The list I get is 3575. I am trying to access the 1,373 list but can't. I want to use it to see how well the query using OMIM aligns with our MONDO annotation.

**Comment by rachellyne** [comment]
It happens with mondo and OMIM so I wonder if it is a problem with the way we have modelled the two disease datasets (as it doesn't seem to happen with other data).

**Comment by ValWood** [comment]
In the first instance , ignore the MONDO because we need to ditch our associations from PombeMIne, and work from human -> pombe instead. I would concentrate on getting the OMIM working

**Comment by danielabutano** [comment]
@ValWood I think it's a bug of the new interface. in the old one, the gene summary is equals to the number of gens saved in the list.

**Comment by heralden** [comment]
Yes, I'm able to reproduce it so I can look into fixing it now.
