### ISSUE TITLE
Unable to constrain boolean values in query builder

### ISSUE THREAD

**Issue by ValWood** [intermine/redgenes#799]
Hi,

We know how to do this, but the relation should be True/ or false (currently gives an error

<img width="567" alt="Screenshot 2022-05-24 at 10 49 16" src="https://user-images.githubusercontent.com/7359272/170248655-998b4d47-57a3-4a3a-9966-788bfd5df3a9.png">

**Comment by heralden** [comment]
Looks like constraining booleans doesn't work properly in Bluegenes. Surprising this hasn't been tested until now. Thanks for reporting!

**Comment by ValWood** [comment]
Any ideas when this will fix. There are quite a few query templates I can't refine or test until this one is working.
Thanks,
Val

**Comment by ValWood** [comment]
It's kind of weird becasue in some instances it works, but others it doesn't.

For example here:
<img width="386" alt="Screenshot 2022-05-30 at 17 46 31" src="https://user-images.githubusercontent.com/7359272/171034291-b65f8279-5092-48a0-8029-cb0be953cffe.png">

I could constrain an ontology term using "contains". (which isn't precise enough to use)
but not using  "equal too" etc

**Comment by ValWood** [comment]
but I do have a query where this constraint is working
http://pombemine.rahtiapp.fi/pombemine/templates/Gene_GOterm

**Comment by ValWood** [comment]
I'm encountering this issues in many places It is making it difficult of r me to construct the desired templates and evaluate the contents.

I encountered another problem for the  "protein domains" class. I can't join on either  
1) species filter
OR
2) "Found in" 
(I'm assuming this is the way to get the genes containing specific domains).

<img width="477" alt="Screenshot 2022-05-31 at 22 58 48" src="https://user-images.githubusercontent.com/7359272/171292371-3e27007a-038e-4c4f-a162-5805f932cfb3.png">

**Comment by heralden** [comment]
> Any ideas when this will fix. There are quite a few query templates I can't refine or test until this one is working.

Sorry about that. I'll look into it and if it's a quick fix we can release it next week.

> I encountered another problem for the "protein domains" class. I can't join on either
> 
>     1. species filter
>        OR
> 
>     2. "Found in"
>        (I'm assuming this is the way to get the genes containing specific domains).

I don't understand what the issue is here. You've added `Protein Domain > Data Sets > Data Source > Description` to the view, which has no value for all of the rows. I think *Found In* and *Organism* also do not have values, so you'll have to remove these 3 or set inner join for all of them.

**Comment by ValWood** [comment]
OK for the domain one, I will work with @kimrutherford next week for how to construct a sensible "protein domains" query linking to a pombe gene.

**Comment by ValWood** [comment]
OK got the domain quer working, so only the boolean constraint  to address here
