### ISSUE TITLE
"with" field attributes separated

### ISSUE THREAD

**Issue by ValWood** [intermine/redgenes#804]
I was wondering why the "with"  field "with text" check box under GO evidence  (top of menu) was separated from the  rest of the "with" field selections (bottom of the menu)

<img width="245" alt="Screenshot 2022-05-30 at 16 48 35" src="https://user-images.githubusercontent.com/7359272/171034670-1136a159-a93c-44c8-9ef2-a239c9ab60bc.png">

**Comment by heralden** [comment]
*With Text* is an attribute of *GO Evidence* while *With* is a reference/collection. Attributes and references/collections are grouped separately and the former is shown first. Both are sorted alphabetically within their group, which is why *With* ends up further down.

**Comment by ValWood** [comment]
Got it!
