### ISSUE TITLE
negative constraint for conditions

### ISSUE THREAD

**Issue by ValWood** [intermine/redgenes#806]
I'm not sure that the "conditions" options are configured correctly.

I can filter on a condition, but I cannot negatively constrain it.

options
<img width="316" alt="Screenshot 2022-05-31 at 13 25 02" src="https://user-images.githubusercontent.com/7359272/171173478-32843c7c-6640-485f-9fa0-88f1107dcd9d.png">

Look up works.

The option "Not in list" seems to be expecting a list?

<img width="1103" alt="Screenshot 2022-05-31 at 13 28 45" src="https://user-images.githubusercontent.com/7359272/171173538-9a9df02d-b4c6-485c-b2b8-59fe73e08e1d.png">

**Comment by ValWood** [comment]
(if you do "edit" on this comment  you can see the XML. I don't know how to make it appear.

```xml
<query model="genomic" view="Gene.primaryIdentifier Gene.symbol Gene.alleles.symbol Gene.alleles.type Gene.alleles.phenotypeAnnotations.ontologyTerm.identifier Gene.alleles.phenotypeAnnotations.ontologyTerm.name Gene.alleles.phenotypeAnnotations.conditions.name" constraintLogic="(A and B)" sortOrder="">
   <constraint path="Gene.alleles.type" value="deletion" op="=" code="A"/>
   <constraint path="Gene.alleles.phenotypeAnnotations.ontologyTerm.name" value="inviable vegetative cell population" op="=" code="B"/>
</query>
```

*Edit: Fixed comment to use code blocks so XML is visible.*

**Comment by heralden** [comment]
If I correctly understood what you're trying to do, you should be adding a constraint to the *Name* attribute under *Condition* instead. If I misunderstood, can you elaborate on "negative constraint"?

**Comment by ValWood** [comment]
I have a list of conditions, but I would like to exclude, for example, "high temperature".

I can only select a condition, but I can't  find a way to exclude a condition.

**Comment by heralden** [comment]
This works properly if you add a constraint on the attribute.

![2022-06-01-141704_618x487_scrot](https://user-images.githubusercontent.com/3865590/171413862-2af498df-65b3-4223-9cb3-6a2db66c4eda.png)

**Comment by ValWood** [comment]
Thanks!
