### ISSUE TITLE
Some high level (i.e GO slim) terms will be unavailable for searching as they do not have direct annotations

### ISSUE THREAD

**Issue by ValWood** [intermine/redgenes#809]
For example "cell cycle"is not an available  search term

Most likely because  at PomBase it has no direct annotations (even though PomBase 632 genes annotated to this term). This is likey to be the case for any groups who follow annotation best practice and annotate as specifically as possible.

<img width="1014" alt="Screenshot 2022-05-31 at 18 21 06" src="https://user-images.githubusercontent.com/7359272/171235211-6e7fc3f1-c99f-454c-aa24-c0822c38f37e.png">

Most people are likely to want to query on grouping terms, and  some grouping terms (for example someGO slim terms), will be unavailable.

**Comment by ValWood** [comment]
For example I just tried with Alliance Mine to access annotations using the grouping term "transport" and this did not appear in the results list (Although this could be because the result appears to be terminating at letter "E"

But I expected with "=" "transport" to find the term if it were there?

**Comment by heralden** [comment]
Does using the *Contains* constraint operation solve your use case?

![2022-06-01-142012_977x649_scrot](https://user-images.githubusercontent.com/3865590/171414526-544e354c-d43e-4b2f-b8d4-5c35b992b8f0.png)

If you want more specific grouping than this, it would have to be done at the data loading step, probably as a new `group` attribute.

**Comment by ValWood** [comment]
No unfortunately  "contains" is just searching for strings in the term names.
So a "substring" search only retrieves 212 rows. I would expect many more than 632 rows (because this is the number of genes that are annotated to descendants of  the GO term "cell cycle). It includes many terms which do not have "cell cycle" in the term name.
For example:
attachment of mitotic spindle microtubules to kinetochore
mitotic actomyosin contractile ring assembly

More generally, I think it is really misleading to have "contains"  for an ontology search that is specifically designed to return all genes annotated to a term. We had that template but I have deleted it. It won't give the correct results.

Because it isn't possible to search for grouping terms unless they are 
directly annotated, this will Increasinglycause more problems , because we  (GO) are making many terms "not for direct annotation" in cases where  it should always be possible to annotate more specifically. As time goes on and annotation gets better, this  problem will be compounded.

I could prepare a workaround by making an additional gaf file with a single redundant annotation to each GO slim term. This is not ideal, as there will be lots of other intermediate terms that are not searchable, and this loses the power of  ontology searching for retrieving all annotations to high level grouping terms. I will think about this for later, but for the demo etc I'll avoid this type of query.

**Comment by heralden** [comment]
I understand. It sounds like we need GO terms to be constrainable by specifying a subset of a tree representing the relationship of GO terms, which for your example would be descendents of cell cycle.

It's an interesting problem and I don't think it's solvable in Intermine now. I guess it would require adding a new  tree node data type for attributes, and constraints on these would support *descendents/ancestors of* tree node.

**Comment by heralden** [comment]
Scratch what I said above. I stumbled over a template on Flymine that does this.

![2022-06-01-165751_1166x651_scrot](https://user-images.githubusercontent.com/3865590/171448364-a2ac4646-4b5b-4256-9127-acc2d792f7e9.png)

```xml
<query model="genomic" view="Gene.secondaryIdentifier Gene.symbol Gene.goAnnotation.ontologyTerm.parents.name Gene.goAnnotation.ontologyTerm.parents.identifier Gene.goAnnotation.ontologyTerm.name Gene.goAnnotation.ontologyTerm.identifier" constraintLogic="(A and B)" sortOrder="Gene.secondaryIdentifier ASC">
   <constraint path="Gene.goAnnotation.ontologyTerm.parents.name" value="DNA binding" op="=" code="A"/>
   <constraint path="Gene.organism.name" value="Drosophila melanogaster" op="=" code="B"/>
   <constraint path="Gene.goAnnotation.ontologyTerm" type="GOTerm"/>
   <constraint path="Gene.goAnnotation.ontologyTerm.parents" type="GOTerm"/>
</query>
```

I see that *ontologyTerm.parents* is also present in Pombemine. Testing with *cell cycle* it seems to work.

![2022-06-01-170432_832x669_scrot](https://user-images.githubusercontent.com/3865590/171449679-a270a5dc-aa04-4bff-aa93-9b1080db34b4.png)

**Comment by ValWood** [comment]
Looks good, will try on Monday!

**Comment by ValWood** [comment]
Thanks! working as expected.
