### ISSUE TITLE
Unable to save list

### ISSUE THREAD

**Issue by ValWood** [intermine/redgenes#810]
<img width="1125" alt="Screenshot 2022-05-31 at 19 37 13" src="https://user-images.githubusercontent.com/7359272/171261168-090720ef-1066-434d-ac7c-afd09b94b0ef.png">

I'm not sure why.
<query model="genomic" view="Gene.primaryIdentifier Gene.uniProtEntry.ecNumbers.identifier" sortOrder="">
</query>

**Comment by heralden** [comment]
I'm not able to reproduce this on Pombemine. Can you give specific instructions for how to create the query which fails to save as list?

**Comment by ValWood** [comment]
This is the XML.

```XML
<query model="genomic" view="Gene.uniProtEntry.ecNumbers.identifier Gene.primaryIdentifier" sortOrder="">
</query>
```

I just retried and still could not save the output as a list.

**Comment by ValWood** [comment]
I just tried again, and this time it worked?

**Comment by heralden** [comment]
I tried it a bunch of times and it succeeded everytime for me. I can only imagine it was a momentary network error.

**Comment by ValWood** [comment]
Odd that I got the error yesterday and today. But I think even when I got the error message, that the lists were saved (I did not check that yesterday).
I'll close this one and let you know if I see the same error again, and try to be more percise.
