### ISSUE TITLE
Cannot acces 'gene' list  for GO query

### ISSUE THREAD

**Issue by ValWood** [intermine/redgenes#811]
I have a template with the following query (Provided by @kimrutherford)  to get all  genes annotated to a GO term  (the query works)

<query model="genomic" view="GOTerm.identifier GOTerm.name GOTerm.ontologyAnnotations.subject.primaryIdentifier GOTerm.parents.identifier GOTerm.parents.name GOTerm.parents.description" constraintLogic="(A)" sortOrder="">
   <constraint path="GOTerm.parents.identifier" value="GO:0003824" op="=" code="A"/>
</query>

However, when I filter the table to get the unique PomBase gene IDs  and send them to the query builder, the created list is of type "Annotatable" not "Gene"

<img width="1121" alt="Screenshot 2022-05-31 at 23 28 27" src="https://user-images.githubusercontent.com/7359272/171294781-78173655-3c5b-4b67-b5e0-9d96b84a68c5.png">

**Comment by heralden** [comment]
> when I filter the table to get the unique PomBase gene IDs and send them to the query builder

I'm not sure how you're doing this. Usually you'd run the template, click save list on the results and choose to save the genes. Then you can use this list for a *In list* constraint for a gene class in the query builder.

![2022-06-01-143035_322x157_scrot](https://user-images.githubusercontent.com/3865590/171416607-e1d879fc-b237-4cdd-9bbc-aaf02339d091.png)

**Comment by ValWood** [comment]
I will get @kimrutherford to explain this to me next week

**Comment by ValWood** [comment]
I think I was doing it correctly, but it all works now. Closing this one.
