### ISSUE TITLE
Show I'mpublic label in template manager for Admins

### ISSUE THREAD

**Issue by ValWood** [intermine/redgenes#813]
It would be really nice if you could see in the template  view which templates are public via a tab. Otherwise it is difficult to know because in the "manage templates". the order is different. 
I have a workaround by just writing this at the beginning of the description.

<img width="1050" alt="Screenshot 2022-06-06 at 14 09 08" src="https://user-images.githubusercontent.com/7359272/172167487-228757d9-f496-46e2-a571-3d829dc06ab0.png">

**Comment by ValWood** [comment]
Low priority, but I think other users would find this useful.

**Comment by heralden** [comment]
I agree this sounds useful. Would be an easy fix as well.

*Implementation notes: Would require similar approach to #737 - check whether tags include `im:public`, then display notice. This would also be useful for regular users so they can differentiate their own templates from the public ones.*
