### ISSUE TITLE
Use lists of type "Gene" in templates

### ISSUE THREAD

**Issue by ValWood** [intermine/redgenes#816]
It would be really nice if, at some point in the future, it could be possible to import/send gene lists directly to a query that is configured to accept a gene list as input (currently need to copy-paste and convert to a comma separated string).

**Comment by heralden** [comment]
This should already be possible. Create a query containing gene, then add an *in list* constraint to the gene class. You will need to select a public list to be used as a default value. It will then pop up under *create template* and you can toggle *editable* for it. This also works similarly for lists containing other types.

**Comment by ValWood** [comment]
Thank you! Kim also mentioned that I could do that this morning. I will add a list option to all of the relevent templates.
