### ISSUE TITLE
make Enrichment widget avaiable to bio-entity DB identifier?

### ISSUE THREAD

**Issue by ValWood** [intermine/redgenes#817]
If I do a query of gene interactors, the interacting gene is represented as a "Bio-entity DB identifier" (even though it is a fission yeast gene.

I can filter on this list but it isn't available to enrichment tools. It would be nice if the enrichment tools were automatically available for "within-species" gene lists.

<img width="1169" alt="Screenshot 2022-06-06 at 21 15 31" src="https://user-images.githubusercontent.com/7359272/172351402-fd5470ff-39d2-428c-8464-ad3ddaba5482.png">
.

**Comment by heralden** [comment]
Usually you don't want to create lists of BioEntity. You can avoid this by setting a type/subclass constraint in your query, which is the dropdown under the class in the model browser.

![2022-06-07-155353_302x62_scrot](https://user-images.githubusercontent.com/3865590/172412246-46232e93-1b24-4ceb-9149-ca6297f70af8.png)
 
Does this solve your problem?

**Comment by ValWood** [comment]
Yes, with @kimrutherford s help. Changed the query to give gene as output.
