### ISSUE TITLE
Column summary is too tall for most screens, pushing its button outside window boundary

### ISSUE THREAD

**Issue by ValWood** [intermine/redgenes#818]
No matter how I adjust on my laptop:

<img width="1362" alt="Screenshot 2022-06-06 at 17 04 49" src="https://user-images.githubusercontent.com/7359272/172351605-4b727197-3a44-4f5d-ab1e-73cddee4aabd.png">

**Comment by heralden** [comment]
If you scroll the page further down, will you be able to access the button? It shouldn't be cut off like that unless it's the boundary of the window.

**Comment by ValWood** [comment]
It is the bottom of the window. That is on a default browser size on a 17 inch MacBookPro screen. The top of the pop up box is quite low  (and fixed)  so the button is out of the window boundary.

**Comment by ValWood** [comment]
This might illustrate more clearly:
<img width="1338" alt="Screenshot 2022-06-07 at 17 22 47" src="https://user-images.githubusercontent.com/7359272/172432781-89f7f0c4-0a5b-4c00-a4dc-54113066788e.png">
This is the default. I can make  my browser window "deeper" but even at full window depth the button is almost out of reach.

**Comment by heralden** [comment]
I guess there's no need for the column summary to be as tall as it is currently. I'll make it shorter.

**Comment by ValWood** [comment]
Just a fraction. Will make demoing easier.
