### ISSUE TITLE
Mine logo URL is hardcoded in nav.cljs rather than given by branding.images.logo

### ISSUE THREAD

**Issue by sammyjava** [intermine/redgenes#828]
A mine's logo URL should always be given by `branding.images.logo` in web.properties. However, it is hardcoded to as `model/images/logo.png` in nav.cljs:
```
src/cljs/bluegenes/components/navbar/nav.cljs:(def ^:const logo-path "/model/images/logo.png")
```
In my case I have 20-odd logos under /model/images for various mines (although I do keep a generic "logo.png" to work around this issue).

**Comment by heralden** [comment]
That value is actually used as a fallback path and `branding.images.logo` is preferred.

Do you have any weird behaviour that might be the result of some flaw in the fallback logic?

**Comment by sammyjava** [comment]
I think I must have messed up branding.images.logo, this issue no longer exists. It is a dead issue. If you'd not nailed it to the perch it'd be pushing up daisies by now! [Monty Python]
